[containers]
base_hosts_file="image"
cgroupns="private"
cgroups="enabled"
default_sysctls = []
ipcns="shareable"
label=false
label_users=false
log_driver="none"
netns="pasta"
pidns="host"
tz="local"
userns="auto"
utsns="host"

[engine]
cgroup_manager="cgroupfs"
runtime="crun"
events_logger="none"
